#!/usr/bin/env python3
"""Freeze a CARLA traffic light by position.
Usage: python3 _tl_freeze.py <x> <y> <sequence>
Sequence format: color:duration,color:duration,...,color
Example: red:10,green:180  (red 10s then green forever)
Auto-generated by VSE OpenSCENARIO export.
"""
import sys, time, carla

STATES = {"GREEN": carla.TrafficLightState.Green,
          "RED": carla.TrafficLightState.Red,
          "YELLOW": carla.TrafficLightState.Yellow,
          "OFF": carla.TrafficLightState.Off}

x, y = float(sys.argv[1]), float(sys.argv[2])
steps = []
for part in sys.argv[3].split(","):
    tokens = part.split(":")
    color = STATES.get(tokens[0].upper())
    if color is None:
        sys.exit(f"Unknown color: {tokens[0]}")
    dur = float(tokens[1]) if len(tokens) > 1 else None
    steps.append((color, dur))

client = carla.Client("localhost", 2000)
client.set_timeout(10.0)
world = client.get_world()
world.wait_for_tick()
tl = None
for actor in world.get_actors().filter("traffic.traffic_light"):
    loc = actor.get_transform().location
    if loc.distance(carla.Location(x, y, loc.z)) < 2.0:
        tl = actor
        break
if tl is None:
    sys.exit(f"No traffic light near ({x}, {y})")

for color, dur in steps:
    tl.set_state(color)
    tl.set_green_time(99999)
    tl.set_red_time(99999)
    tl.set_yellow_time(99999)
    if dur is not None:
        time.sleep(dur)
